title: Paperlogos
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2639123
  lightness: 0
  brandStrength: 0.5657673
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  rhythmicContrast: 0.6315346
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: PaperLogos
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.40839
layout_spectrum: 0
