name: PaperLogos
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3249194
title: Paperlogos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.875
  lightness: 0.9113855
  saturation: 0.1863587
  rhythmicContrast: 0.5977443
purpose: []
